### ISSUE TITLE
Deprecation warning with Ruby 2.7+

### ISSUE THREAD

**Issue by krnjn** [kklimuk/memoized#1]
Hi @kklimuk -- really appreciate this utility / gem. I am attempting an upgrade to Ruby 2.7 in my own projects and receive a deprecation warning from the gem of:

```rb
ruby_memoized-0.1.2/lib/ruby_memoized/memoizer.rb:12: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

I'm not sure if you've seen it already or read the [Ruby 2.7 deprecation announcement](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) regarding the keyword args. I found this blog post helpful when upgrading our codebase: https://blog.bigbinary.com/2020/04/14/ruby-2-7-deprecates-conversion-of-keyword-arguments.html

**Comment by kklimuk** [comment]
Hey @krnjn! Happy to fix this if you don't mind reviewing.

**Comment by kklimuk** [comment]
PR here: https://github.com/kklimuk/ruby_memoized/pull/2

**Comment by kklimuk** [comment]
Closing since the fix is published: https://rubygems.org/gems/ruby_memoized/versions/0.1.3
Thanks @krnjn!
